-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_DOCUMENT_REQUESTED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_INTERVIEW_PROPOSED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_ADMISSION_LETTER_ISSUED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_ACCEPTED_PENDING_TRAVEL_CONSENT';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_TRAVEL_CONSENT_CONFIRMED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_AGREEMENT_FULLY_SIGNED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_ESTABLISHMENT_SIGNED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_CLOSED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_RECOMMENDATION_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_RECEIVED_ORG';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_DOCUMENT_SUBMITTED_ORG';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_INTERVIEW_CONFIRMED_ORG';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_ADMISSION_ACCEPTED_ORG';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_TRAVEL_CONSENT_CONFIRMED_ORG';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_AGREEMENT_FULLY_SIGNED_ORG';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_ESTABLISHMENT_SIGNED_ORG';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_WITHDRAWN_ORG';
ALTER TYPE "NotificationType" ADD VALUE 'APPLICATION_ESTABLISHMENT_ASSOCIATION_REQUESTED';
ALTER TYPE "NotificationType" ADD VALUE 'LEARNER_INVITED';
ALTER TYPE "NotificationType" ADD VALUE 'LEARNER_VERIFIED';
ALTER TYPE "NotificationType" ADD VALUE 'INTERNSHIP_REPORT_REVIEWED';
ALTER TYPE "NotificationType" ADD VALUE 'ORGANIZATION_INVITATION_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE 'ORGANIZATION_ACCESS_REVOKED';
ALTER TYPE "NotificationType" ADD VALUE 'NEED_REQUEST_ANSWERED';
